"""included user phone number for signal integration

Revision ID: 026c79f615b5
Revises: d5b4bf0e0ec7
Create Date: 2026-05-14 15:19:46.228869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026c79f615b5'
down_revision = 'd5b4bf0e0ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_no', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_no')

    # ### end Alembic commands ###
