"""added beer ledger connections to user

Revision ID: 28a223f6c8eb
Revises: c30291536e1c
Create Date: 2026-05-03 08:05:04.296177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a223f6c8eb'
down_revision = 'c30291536e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beer_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debtor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('creditor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_beer_ledger_debtor', 'user', ['debtor_id'], ['id'])
        batch_op.create_foreign_key('fk_beer_ledger_creditor', 'user', ['creditor_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beer_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_beer_ledger_creditor', type_='foreignkey')
        batch_op.drop_constraint('fk_beer_ledger_debtor', type_='foreignkey')
        batch_op.create_foreign_key('fk_beer_ledger_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('creditor_id')
        batch_op.drop_column('debtor_id')

    # ### end Alembic commands ###
