"""added bingo card position

Revision ID: 3585b86ddb49
Revises: 42b3a66caf59
Create Date: 2026-03-16 12:20:31.175503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3585b86ddb49'
down_revision = '42b3a66caf59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer()))
        batch_op.create_unique_constraint('uq_user_category_position', ['user_id', 'category', 'position'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_category_position', type_='unique')
        batch_op.drop_column('position')

    # ### end Alembic commands ###
