"""New PredictionConclusion and Vote models to finish predictions

Revision ID: 42b3a66caf59
Revises: cdddc2832267
Create Date: 2026-03-10 15:41:52.198555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b3a66caf59'
down_revision = 'cdddc2832267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_conclusion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('SUCCESS', 'FAILED', name='conclusionoutcome'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='conclusionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_conclusion_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prediction_conclusion_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_conclusion_id'], ['prediction_conclusion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'prediction_conclusion_id', name='_user_prediction_conclusion_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_conclusion_vote')
    op.drop_table('prediction_conclusion')
    # ### end Alembic commands ###
