"""added open and closing deadline for bets

Revision ID: 547485a7e17a
Revises: 83eec71e5690
Create Date: 2026-04-25 12:05:20.131032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547485a7e17a'
down_revision = '83eec71e5690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_until', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('close_by', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_column('close_by')
        batch_op.drop_column('vote_until')

    # ### end Alembic commands ###
