"""added bingo multiplier

Revision ID: 598df4d5c314
Revises: 3585b86ddb49
Create Date: 2026-03-16 13:14:33.201744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598df4d5c314'
down_revision = '3585b86ddb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multiplier', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('multiplier')

    # ### end Alembic commands ###
