"""updated achievement user association to have single ID

Revision ID: 6d2d5471ac9c
Revises: cfaa518076e9
Create Date: 2026-01-18 12:51:35.597249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2d5471ac9c'
down_revision = 'cfaa518076e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('_user_achievement_uc', ['user_id', 'achievement_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.drop_constraint('_user_achievement_uc', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
