"""removed duplicate issues with achievements

Revision ID: 6e0bf6cfd096
Revises: 70f79017b91e
Create Date: 2026-01-22 19:01:27.741284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0bf6cfd096'
down_revision = '70f79017b91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_achievements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievements',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('achievement_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    # ### end Alembic commands ###
