"""Added stock picks and price updates

Revision ID: e80e347dd019
Revises: 5eeac8f54025
Create Date: 2026-01-19 21:18:41.181279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80e347dd019'
down_revision = '5eeac8f54025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockpick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=12), nullable=False),
    sa.Column('country', sa.String(length=12), nullable=False),
    sa.Column('ceo', sa.String(length=64), nullable=False),
    sa.Column('exchange_full_name', sa.String(length=128), nullable=False),
    sa.Column('exchange', sa.String(length=12), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=False),
    sa.Column('employees', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=False),
    sa.Column('last_checked', sa.Date(), nullable=True),
    sa.Column('initial_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='_user_symbol_uc')
    )
    op.create_table('stockupdate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change', sa.Float(), nullable=False),
    sa.Column('change_percentage', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('market_cap', sa.BigInteger(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('average_volume', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stockpick.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockupdate')
    op.drop_table('stockpick')
    # ### end Alembic commands ###
